package com.fastcode.example.domain.Temp;

import java.time.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "DVDRENTAL", name = "ADDRESS")
public class Address {

    @Basic
    @Column(nullable = false, length = 50)
    private String address;

    @Basic
    @Column(length = 50)
    private String address2;

    @Id
    @Column(name = "ADDRESS_ID")
    private int addressId;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "CITY_ID", nullable = false)
    private City city;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Customer.class,
        mappedBy = "address",
        cascade = CascadeType.MERGE
    )
    private Set<Customer> customers = new HashSet<Customer>();

    @Basic
    @Column(nullable = false, length = 20)
    private String district;

    @Basic
    @Column(name = "LAST_UPDATE", nullable = false)
    private LocalDateTime lastUpdate;

    @Basic
    @Column(nullable = false, length = 20)
    private String phone;

    @Basic
    @Column(name = "POSTAL_CODE", length = 10)
    private String postalCode;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Staff.class,
        mappedBy = "address",
        cascade = CascadeType.MERGE
    )
    private Set<Staff> staffs = new HashSet<Staff>();

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Store.class,
        mappedBy = "address",
        cascade = CascadeType.MERGE
    )
    private Set<Store> stores = new HashSet<Store>();

    public Address() {}

    public Address(int addressId) {
        this.addressId = addressId;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public int getAddressId() {
        return addressId;
    }

    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public Set<Customer> getCustomers() {
        return customers;
    }

    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public Set<Staff> getStaffs() {
        return staffs;
    }

    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }

    public Set<Store> getStores() {
        return stores;
    }

    public void setStores(Set<Store> stores) {
        this.stores = stores;
    }
}
