package com.fastcode.example.domain.Temp;

import java.time.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "DVDRENTAL", name = "CATEGORY")
public class Category {

    @Id
    @Column(name = "CATEGORY_ID")
    private int categoryId;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.FilmCategory.class,
        mappedBy = "category",
        cascade = CascadeType.MERGE
    )
    private Set<FilmCategory> filmCategorys = new HashSet<FilmCategory>();

    @Basic
    @Column(name = "LAST_UPDATE", nullable = false)
    private LocalDateTime lastUpdate;

    @Basic
    @Column(nullable = false, length = 25)
    private String name;

    public Category() {}

    public Category(int categoryId) {
        this.categoryId = categoryId;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public Set<FilmCategory> getFilmCategorys() {
        return filmCategorys;
    }

    public void setFilmCategorys(Set<FilmCategory> filmCategorys) {
        this.filmCategorys = filmCategorys;
    }

    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
