package com.fastcode.example.domain.Temp;

import java.time.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "DVDRENTAL", name = "COUNTRY")
public class Country {

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.City.class,
        mappedBy = "country",
        cascade = CascadeType.MERGE
    )
    private Set<City> citys = new HashSet<City>();

    @Basic
    @Column(nullable = false, length = 50)
    private String country;

    @Id
    @Column(name = "COUNTRY_ID")
    private int countryId;

    @Basic
    @Column(name = "LAST_UPDATE", nullable = false)
    private LocalDateTime lastUpdate;

    public Country() {}

    public Country(int countryId) {
        this.countryId = countryId;
    }

    public Set<City> getCitys() {
        return citys;
    }

    public void setCitys(Set<City> citys) {
        this.citys = citys;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public int getCountryId() {
        return countryId;
    }

    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}
