package com.fastcode.example.domain.Temp;

import java.time.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "DVDRENTAL", name = "CUSTOMER")
public class Customer {

    @Basic
    private Integer active;

    @Basic
    @Column(nullable = false, length = 1)
    private byte[] activebool;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ADDRESS_ID", nullable = false)
    private Address address;

    @Basic
    @Column(name = "CREATE_DATE", nullable = false)
    private LocalDate createDate;

    @Id
    @Column(name = "CUSTOMER_ID")
    private int customerId;

    @Basic
    @Column(length = 50)
    private String email;

    @Basic
    @Column(name = "FIRST_NAME", nullable = false, length = 50)
    private String firstName;

    @Basic
    @Column(name = "LAST_NAME", nullable = false, length = 50)
    private String lastName;

    @Basic
    @Column(name = "LAST_UPDATE")
    private LocalDateTime lastUpdate;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Payment.class,
        mappedBy = "customer",
        cascade = CascadeType.MERGE
    )
    private Set<Payment> payments = new HashSet<Payment>();

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Rental.class,
        mappedBy = "customer",
        cascade = CascadeType.MERGE
    )
    private Set<Rental> rentals = new HashSet<Rental>();

    @Basic
    @Column(name = "STORE_ID")
    private short storeId;

    public Customer() {}

    public Customer(int customerId) {
        this.customerId = customerId;
    }

    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

    public byte[] getActivebool() {
        return activebool;
    }

    public void setActivebool(byte[] activebool) {
        this.activebool = activebool;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public LocalDate getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDate createDate) {
        this.createDate = createDate;
    }

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Set<Payment> getPayments() {
        return payments;
    }

    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

    public Set<Rental> getRentals() {
        return rentals;
    }

    public void setRentals(Set<Rental> rentals) {
        this.rentals = rentals;
    }

    public short getStoreId() {
        return storeId;
    }

    public void setStoreId(short storeId) {
        this.storeId = storeId;
    }
}
