package com.fastcode.example.domain.Temp;

import java.math.*;
import java.time.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "DVDRENTAL", name = "FILM")
public class Film {

    @Basic
    @Lob
    private String description;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.FilmActor.class,
        mappedBy = "film",
        cascade = CascadeType.MERGE
    )
    private Set<FilmActor> filmActors = new HashSet<FilmActor>();

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.FilmCategory.class,
        mappedBy = "film",
        cascade = CascadeType.MERGE
    )
    private Set<FilmCategory> filmCategorys = new HashSet<FilmCategory>();

    @Id
    @Column(name = "FILM_ID")
    private int filmId;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Inventory.class,
        mappedBy = "film",
        cascade = CascadeType.MERGE
    )
    private Set<Inventory> inventorys = new HashSet<Inventory>();

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "LANGUAGE_ID", nullable = false)
    private Language language;

    @Basic
    @Column(name = "LAST_UPDATE", nullable = false)
    private LocalDateTime lastUpdate;

    @Basic
    private Short length;

    @Basic
    private String rating;

    @Basic
    @Column(name = "RELEASE_YEAR")
    private Integer releaseYear;

    @Basic
    @Column(name = "RENTAL_DURATION")
    private short rentalDuration;

    @Basic
    @Column(name = "RENTAL_RATE", nullable = false)
    private BigDecimal rentalRate;

    @Basic
    @Column(name = "REPLACEMENT_COST", nullable = false)
    private BigDecimal replacementCost;

    @Basic
    @Column(nullable = false)
    private String title;

    public Film() {}

    public Film(int filmId) {
        this.filmId = filmId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<FilmActor> getFilmActors() {
        return filmActors;
    }

    public void setFilmActors(Set<FilmActor> filmActors) {
        this.filmActors = filmActors;
    }

    public Set<FilmCategory> getFilmCategorys() {
        return filmCategorys;
    }

    public void setFilmCategorys(Set<FilmCategory> filmCategorys) {
        this.filmCategorys = filmCategorys;
    }

    public int getFilmId() {
        return filmId;
    }

    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }

    public Set<Inventory> getInventorys() {
        return inventorys;
    }

    public void setInventorys(Set<Inventory> inventorys) {
        this.inventorys = inventorys;
    }

    public Language getLanguage() {
        return language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Short getLength() {
        return length;
    }

    public void setLength(Short length) {
        this.length = length;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public Integer getReleaseYear() {
        return releaseYear;
    }

    public void setReleaseYear(Integer releaseYear) {
        this.releaseYear = releaseYear;
    }

    public short getRentalDuration() {
        return rentalDuration;
    }

    public void setRentalDuration(short rentalDuration) {
        this.rentalDuration = rentalDuration;
    }

    public BigDecimal getRentalRate() {
        return rentalRate;
    }

    public void setRentalRate(BigDecimal rentalRate) {
        this.rentalRate = rentalRate;
    }

    public BigDecimal getReplacementCost() {
        return replacementCost;
    }

    public void setReplacementCost(BigDecimal replacementCost) {
        this.replacementCost = replacementCost;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
