package com.fastcode.example.domain.Temp;

import java.time.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema = "DVDRENTAL", name = "STAFF")
public class Staff {

    @Basic
    @Column(nullable = false, length = 1)
    private byte[] active;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
    @JoinColumn(name = "ADDRESS_ID", nullable = false)
    private Address address;

    @Basic
    @Column(length = 50)
    private String email;

    @Basic
    @Column(name = "FIRST_NAME", nullable = false, length = 45)
    private String firstName;

    @Basic
    @Column(name = "LAST_NAME", nullable = false, length = 45)
    private String lastName;

    @Basic
    @Column(name = "LAST_UPDATE", nullable = false)
    private LocalDateTime lastUpdate;

    @Basic
    @Column(length = 40)
    private String password;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Payment.class,
        mappedBy = "staff",
        cascade = CascadeType.MERGE
    )
    private Set<Payment> payments = new HashSet<Payment>();

    @Basic
    @Column(length = 2147483647)
    private byte[] picture;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Rental.class,
        mappedBy = "staff",
        cascade = CascadeType.MERGE
    )
    private Set<Rental> rentals = new HashSet<Rental>();

    @Id
    @Column(name = "STAFF_ID")
    private int staffId;

    @Basic
    @Column(name = "STORE_ID")
    private short storeId;

    @OneToMany(
        targetEntity = com.fastcode.example.domain.Temp.Store.class,
        mappedBy = "staff",
        cascade = CascadeType.MERGE
    )
    private Set<Store> stores = new HashSet<Store>();

    @Basic
    @Column(nullable = false, length = 16)
    private String username;

    public Staff() {}

    public Staff(int staffId) {
        this.staffId = staffId;
    }

    public byte[] getActive() {
        return active;
    }

    public void setActive(byte[] active) {
        this.active = active;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<Payment> getPayments() {
        return payments;
    }

    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

    public byte[] getPicture() {
        return picture;
    }

    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    public Set<Rental> getRentals() {
        return rentals;
    }

    public void setRentals(Set<Rental> rentals) {
        this.rentals = rentals;
    }

    public int getStaffId() {
        return staffId;
    }

    public void setStaffId(int staffId) {
        this.staffId = staffId;
    }

    public short getStoreId() {
        return storeId;
    }

    public void setStoreId(short storeId) {
        this.storeId = storeId;
    }

    public Set<Store> getStores() {
        return stores;
    }

    public void setStores(Set<Store> stores) {
        this.stores = stores;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
